# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fortune_pb2 as fortune__pb2


class FortuneTellerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/build.stack.fortune.FortuneTeller/Predict',
        request_serializer=fortune__pb2.PredictionRequest.SerializeToString,
        response_deserializer=fortune__pb2.PredictionResponse.FromString,
        )


class FortuneTellerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FortuneTellerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=fortune__pb2.PredictionRequest.FromString,
          response_serializer=fortune__pb2.PredictionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'build.stack.fortune.FortuneTeller', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
