# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fortune.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fortune.proto',
  package='build.stack.fortune',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rfortune.proto\x12\x13\x62uild.stack.fortune\"\x13\n\x11PredictionRequest\"%\n\x12PredictionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2k\n\rFortuneTeller\x12Z\n\x07Predict\x12&.build.stack.fortune.PredictionRequest\x1a\'.build.stack.fortune.PredictionResponseb\x06proto3')
)




_PREDICTIONREQUEST = _descriptor.Descriptor(
  name='PredictionRequest',
  full_name='build.stack.fortune.PredictionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=57,
)


_PREDICTIONRESPONSE = _descriptor.Descriptor(
  name='PredictionResponse',
  full_name='build.stack.fortune.PredictionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='build.stack.fortune.PredictionResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['PredictionRequest'] = _PREDICTIONREQUEST
DESCRIPTOR.message_types_by_name['PredictionResponse'] = _PREDICTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PredictionRequest = _reflection.GeneratedProtocolMessageType('PredictionRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTIONREQUEST,
  __module__ = 'fortune_pb2'
  # @@protoc_insertion_point(class_scope:build.stack.fortune.PredictionRequest)
  ))
_sym_db.RegisterMessage(PredictionRequest)

PredictionResponse = _reflection.GeneratedProtocolMessageType('PredictionResponse', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTIONRESPONSE,
  __module__ = 'fortune_pb2'
  # @@protoc_insertion_point(class_scope:build.stack.fortune.PredictionResponse)
  ))
_sym_db.RegisterMessage(PredictionResponse)



_FORTUNETELLER = _descriptor.ServiceDescriptor(
  name='FortuneTeller',
  full_name='build.stack.fortune.FortuneTeller',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=98,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='build.stack.fortune.FortuneTeller.Predict',
    index=0,
    containing_service=None,
    input_type=_PREDICTIONREQUEST,
    output_type=_PREDICTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FORTUNETELLER)

DESCRIPTOR.services_by_name['FortuneTeller'] = _FORTUNETELLER

# @@protoc_insertion_point(module_scope)
