# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='getid.proto',
  package='getid',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bgetid.proto\x12\x05getid\"\x0b\n\tIDRequest\"\x1a\n\x07IDReply\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x0bInformation\x12/\n\tRequestID\x12\x10.getid.IDRequest\x1a\x0e.getid.IDReply\"\x00\x62\x06proto3')
)




_IDREQUEST = _descriptor.Descriptor(
  name='IDRequest',
  full_name='getid.IDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=33,
)


_IDREPLY = _descriptor.Descriptor(
  name='IDReply',
  full_name='getid.IDReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='getid.IDReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['IDRequest'] = _IDREQUEST
DESCRIPTOR.message_types_by_name['IDReply'] = _IDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IDRequest = _reflection.GeneratedProtocolMessageType('IDRequest', (_message.Message,), dict(
  DESCRIPTOR = _IDREQUEST,
  __module__ = 'getid_pb2'
  # @@protoc_insertion_point(class_scope:getid.IDRequest)
  ))
_sym_db.RegisterMessage(IDRequest)

IDReply = _reflection.GeneratedProtocolMessageType('IDReply', (_message.Message,), dict(
  DESCRIPTOR = _IDREPLY,
  __module__ = 'getid_pb2'
  # @@protoc_insertion_point(class_scope:getid.IDReply)
  ))
_sym_db.RegisterMessage(IDReply)



_INFORMATION = _descriptor.ServiceDescriptor(
  name='Information',
  full_name='getid.Information',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=63,
  serialized_end=125,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestID',
    full_name='getid.Information.RequestID',
    index=0,
    containing_service=None,
    input_type=_IDREQUEST,
    output_type=_IDREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INFORMATION)

DESCRIPTOR.services_by_name['Information'] = _INFORMATION

# @@protoc_insertion_point(module_scope)
